[phases.setup]
nixPkgs = ["python312", "uv", "unzip"]

[phases.install]
cmds = [
  "uv sync --frozen"
]

[start]
cmd = "uv run reflex run --env prod --single-port --backend-host 0.0.0.0 --backend-port $PORT"
